"""initial migration

Revision ID: 3781c76635fe
Revises: 
Create Date: 2026-07-05 04:07:37.462902+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3781c76635fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Category name (e.g., Music, Sports, Technology)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the category'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False, comment='Timestamp when category was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address — used for login, must be unique'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Display username — must be unique'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt-hashed password — NEVER store plaintext'),
    sa.Column('full_name', sa.String(length=200), nullable=True, comment='Optional full name for display purposes'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete / account activation flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last profile update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Event title shown on listing and detail pages'),
    sa.Column('description', sa.Text(), nullable=True, comment='Full event description — used for TF-IDF content-based filtering'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='FK to categories table — SET NULL if category is deleted'),
    sa.Column('venue', sa.String(length=300), nullable=True, comment='Venue name or address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City where the event takes place — used for location-based filtering'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Event start date and time'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='Event end date and time (optional)'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False, comment='Ticket price in VND (0 = free)'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Maximum number of attendees (NULL = unlimited)'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment="Comma-separated tags for content-based filtering (e.g., 'music,outdoor,festival'). Parsed by the ML training pipeline."),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft delete flag — inactive events are hidden from listings'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False, comment='Timestamp when the event was created'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_category_id', 'events', ['category_id'], unique=False)
    op.create_index(op.f('ix_events_city'), 'events', ['city'], unique=False)
    op.create_index('ix_events_start_date', 'events', ['start_date'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK to users — delete reviews when user is deleted'),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='FK to events — delete reviews when event is deleted'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Numeric rating from 1 (worst) to 5 (best)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Review text — input for sentiment analysis ML model'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment='ML model prediction: positive | neutral | negative. NULL if model has not run yet or prediction failed.'),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True, comment='Confidence score of the sentiment prediction (0.0–1.0). NULL if sentiment_label is NULL.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False, comment='When the review was submitted'),
    sa.CheckConstraint("sentiment_label IS NULL OR sentiment_label IN ('positive', 'neutral', 'negative')", name='ck_review_sentiment_label'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_review_user_event')
    )
    op.create_index('ix_reviews_event_id', 'reviews', ['event_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK to users — delete interactions when user is deleted'),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='FK to events — delete interactions when event is deleted'),
    sa.Column('interaction_type', sa.String(length=50), nullable=False, comment='Type of interaction: view | click | favorite | register'),
    sa.Column('interaction_score', sa.Float(), server_default='1.0', nullable=False, comment='Implicit feedback score: view=1.0, click=2.0, favorite=2.5, register=3.0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('getdate()'), nullable=False, comment='When the interaction occurred'),
    sa.CheckConstraint("interaction_type IN ('view', 'click', 'favorite', 'register')", name='ck_interaction_type'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_interactions_user_event', 'user_interactions', ['user_id', 'event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_interactions_user_event', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_event_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_events_start_date', table_name='events')
    op.drop_index(op.f('ix_events_city'), table_name='events')
    op.drop_index('ix_events_category_id', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
